import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { TRPCReactProvider } from "~/trpc/react";
import { ourFileRouter } from "./api/uploadthing/uploadthing";
import { extractRouterConfig } from "uploadthing/server";
import TopNav from "./_components/NavBar";
import Navbar from "./_components/NewNavBar/Navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "./_components/SessionProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const  session = await getServerSession();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
        <SessionProvider session={session}>

        <Navbar/>
          {children}
          </SessionProvider>
          </TRPCReactProvider>
      </body>
    </html>
  );
}
