import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { TRPCReactProvider } from "~/trpc/react";
import { ourFileRouter } from "./api/uploadthing/uploadthing";
import { extractRouterConfig } from "uploadthing/server";
import TopNav from "./_components/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
      {/* <TopNav/> */}

        <TRPCReactProvider>
        {/* <NextSSRPlugin
          routerConfig={extractRouterConfig(ourFileRouter)}
        /> */}
          {children}</TRPCReactProvider>
      </body>
    </html>
  );
}
